// <auto-generated />
using Ath_Thoyyibah_BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;

#nullable disable

namespace Ath_Thoyyibah_BE.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.APIKeyCollection", b =>
                {
                    b.Property<int>("APIKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("APIName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("APIKeyId");

                    b.ToTable("APIKeyCollection");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.ApplicationUser", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("dateofBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("education")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("firstName")
                        .HasColumnType("longtext");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("lastName")
                        .HasColumnType("longtext");

                    b.Property<int>("lmby")
                        .HasColumnType("int");

                    b.Property<DateTime>("lmdt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("photoURL")
                        .HasColumnType("longtext");

                    b.Property<string>("referalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("remarks")
                        .HasColumnType("longtext");

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.Property<string>("sex")
                        .HasColumnType("longtext");

                    b.Property<int>("subscriptionId")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.BankAccountUsers", b =>
                {
                    b.Property<int>("BankAccountUsersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BankAccountUsersId");

                    b.ToTable("BankAccountUsers");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.ContactUsMessage", b =>
                {
                    b.Property<int>("contactUsMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("contactUsMessageId");

                    b.ToTable("ContactUsMessage");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.ContentManagementMaster", b =>
                {
                    b.Property<int>("ContentManagementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsLogedIn")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LMBY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LMDT")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TitleContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ContentManagementId");

                    b.ToTable("ContentManagementMaster");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.GreenGroceries", b =>
                {
                    b.Property<int>("GreenGroceryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GroceryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LMBY")
                        .HasColumnType("int");

                    b.Property<DateTime>("LMDT")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GreenGroceryId");

                    b.ToTable("GreenGroceries");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.MasterBankAccount", b =>
                {
                    b.Property<int>("BankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BankLogo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("BankAccountId");

                    b.ToTable("MasterBankAccount");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.MasterBanks", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BankLogo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("BankId");

                    b.ToTable("MasterBanks");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.MasterIngredients", b =>
                {
                    b.Property<int>("IngredientsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("IngridientCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("LMBY")
                        .HasColumnType("int");

                    b.Property<DateTime>("LMDT")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QTY")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RequestBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UOM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IngredientsId");

                    b.ToTable("MasterIngredients");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.MasterIngridientCategory", b =>
                {
                    b.Property<int>("IngridientCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CategoryIngridientName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LMBY")
                        .HasColumnType("int");

                    b.Property<DateTime>("LMDT")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IngridientCategoryId");

                    b.ToTable("MasterIngridientCategory");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.MasterUoms", b =>
                {
                    b.Property<int>("UomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("LMBY")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LMDT")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UomName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UomId");

                    b.ToTable("MasterUoms");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.Members", b =>
                {
                    b.Property<int>("memberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("education")
                        .HasColumnType("longtext");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("lmby")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("lmdt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("pairingUserId")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("photoBase64")
                        .HasColumnType("longtext");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("memberId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.MenuIngredients", b =>
                {
                    b.Property<int>("MenuIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IngredientsId")
                        .HasColumnType("int");

                    b.Property<string>("LMBY")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LMDT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UomId")
                        .HasColumnType("int");

                    b.HasKey("MenuIngredientId");

                    b.ToTable("MenuIngredients");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.MenuSchedule", b =>
                {
                    b.Property<int>("MenuScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("lmby")
                        .HasColumnType("int");

                    b.Property<DateTime>("lmdt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MenuScheduleId");

                    b.ToTable("MenuSchedule");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.Menus", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LMBY")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LMDT")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoURL")
                        .HasColumnType("longtext");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("VideoURL")
                        .HasColumnType("longtext");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.MobileNotification", b =>
                {
                    b.Property<int>("MobileNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LMBY")
                        .HasColumnType("int");

                    b.Property<DateTime>("LMDT")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("deviceId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("MobileNotificationId");

                    b.ToTable("MobileNotification");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.OTPUsers", b =>
                {
                    b.Property<int>("OTPUsersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("OTP")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ValidStart")
                        .HasColumnType("datetime(6)");

                    b.HasKey("OTPUsersId");

                    b.ToTable("OTPUsers");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.ReferalBonusClaim", b =>
                {
                    b.Property<int>("ReferalBonusClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ApprovedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BankTransfer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ClaimedAmount")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TransferEvidence")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReferalBonusClaimId");

                    b.ToTable("ReferalBonusClaim");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.ShopingCart", b =>
                {
                    b.Property<int>("ShopingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReservedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ShopingCartId");

                    b.ToTable("ShopingCart");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.ShopingTransactions", b =>
                {
                    b.Property<int>("ShoppingTranscationsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IngredientsId")
                        .HasColumnType("int");

                    b.Property<int>("LMBY")
                        .HasColumnType("int");

                    b.Property<DateTime>("LMDT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UoM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ShoppingTranscationsId");

                    b.ToTable("ShopingTransactions");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.SubcriptionEvidences", b =>
                {
                    b.Property<int>("SubcriptionEvidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("activateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("evidenceBase64")
                        .HasColumnType("longtext");

                    b.Property<string>("evidenceFile")
                        .HasColumnType("longtext");

                    b.Property<string>("evidenceURL")
                        .HasColumnType("longtext");

                    b.Property<bool>("isValid")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("subsPeriodId")
                        .HasColumnType("int");

                    b.Property<string>("transferBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("transferDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("userEmail")
                        .HasColumnType("longtext");

                    b.HasKey("SubcriptionEvidenceId");

                    b.ToTable("SubcriptionEvidences");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.SubscriptionPeriods", b =>
                {
                    b.Property<int>("subscriptionPeriodsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("period")
                        .HasColumnType("int");

                    b.Property<string>("periodName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("referalBonus")
                        .HasColumnType("int");

                    b.Property<int>("unitConversion")
                        .HasColumnType("int");

                    b.HasKey("subscriptionPeriodsId");

                    b.ToTable("SubscriptionPeriods");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.TipsTricks", b =>
                {
                    b.Property<int>("TipsTricksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NamaTipsTricks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("createdBy")
                        .HasColumnType("int");

                    b.Property<bool>("isPublished")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("TipsTricksId");

                    b.ToTable("TipsTricks");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.TipsTricksSaved", b =>
                {
                    b.Property<int>("tipsTricksSavedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("createdBy")
                        .HasColumnType("int");

                    b.Property<int>("tipsTricksId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("tipsTricksSavedId");

                    b.ToTable("TipsTricksSaved");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.UserPayments", b =>
                {
                    b.Property<int>("userPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<bool>("isValid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("orderId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("paymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("paymentStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("taxAmount")
                        .HasColumnType("int");

                    b.Property<int>("totalAmount")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("userPaymentId");

                    b.ToTable("UserPayments");
                });

            modelBuilder.Entity("Ath_Thoyyibah_BE.Models.UserReferals", b =>
                {
                    b.Property<int>("userReferalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("lmby")
                        .HasColumnType("int");

                    b.Property<DateTime>("lmdt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("referalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("referalOwnerBonus")
                        .HasColumnType("int");

                    b.Property<int>("referalUserBonus")
                        .HasColumnType("int");

                    b.Property<int>("registeredUserId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("userReferalId");

                    b.ToTable("UserReferals");
                });
#pragma warning restore 612, 618
        }
    }
}
